apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:admin@mongo-0.mongo-headless.taskify.svc.cluster.local:27017/Taskify?authSource=admin&replicaSet=rs0&retryWrites=true&w=majority"
  PORT: "3000"
  JWT_SECRET: "STRONG+KEY"
