# mongo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo  # Must match your mongo deployment's labels
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
