apiVersion: v1
kind: Secret
metadata:
  name: tasks-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:admin@mongo-0.mongo.taskify.svc.cluster.local:27017,mongo-1.mongo.taskify.svc.cluster.local:27017,mongo-2.mongo.taskify.svc.cluster.local:27017/admin?replicaSet=rs0"
  PORT: "3000"
  JWT_SECRET: "STRONG+KEY"
  AUTH_SVC_URL: "auth-service.taskify.svc.cluster.local"
