import { StyleSheet, Platform } from 'react-native';
import { SPACING, RADIUS } from '@/src/constants/theme';

export const getStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    subHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.sm,
    },
    headerLeft: {
        flex: 1,
    },
    title: {
        fontSize: 26,
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -0.5,
    },
    subtitle: {
        fontSize: 13,
        color: colors.textSecondary,
        marginTop: 2,
    },
    addBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.primary15,
        alignItems: 'center',
        justifyContent: 'center',
    },
    listContent: {
        padding: SPACING.lg,
        paddingBottom: 120,
    },
    ideaCard: {
        backgroundColor: colors.card,
        borderRadius: RADIUS.lg,
        padding: SPACING.md,
        marginBottom: SPACING.md,
        borderWidth: 1,
        borderColor: colors.border,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.06,
                shadowRadius: 4,
            },
            android: { elevation: 2 },
        }),
    },
    ideaCardNew: {
        borderLeftWidth: 3,
        borderLeftColor: colors.primary,
    },
    ideaHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: SPACING.sm,
    },
    ideaTitleContainer: {
        flex: 1,
    },
    ideaTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.text,
        lineHeight: 22,
    },
    ideaDescription: {
        fontSize: 13,
        color: colors.textSecondary,
        marginTop: 6,
        lineHeight: 18,
    },
    ideaMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: SPACING.sm,
        gap: SPACING.md,
    },
    metaText: {
        fontSize: 11,
        color: colors.textSecondary,
    },
    threadBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primary15,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
        gap: 4,
    },
    threadBadgeText: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.primary,
    },
    ideaActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    iconButton: {
        padding: 6,
        borderRadius: 8,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 80,
        paddingHorizontal: SPACING.xl,
    },
    emptyIcon: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: colors.primary15,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: SPACING.lg,
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: colors.text,
        textAlign: 'center',
        marginBottom: SPACING.sm,
    },
    emptyText: {
        fontSize: 14,
        color: colors.textSecondary,
        textAlign: 'center',
        lineHeight: 20,
    },
    fab: {
        position: 'absolute',
        bottom: SPACING.xl,
        right: SPACING.xl,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        boxShadow: '0 4px 4px 0 rgba(0, 0, 0, 0.3)',
    },
    fabTouch: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: colors.overlay,
        zIndex: 98,
    },
    compactModalContainer: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'flex-end',
        backgroundColor: 'transparent',
    },
    // Thread modal styles
    threadModalOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: colors.overlay,
        zIndex: 200,
    },
    threadModal: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        top: '10%',
        backgroundColor: colors.card,
        borderTopLeftRadius: RADIUS.xl,
        borderTopRightRadius: RADIUS.xl,
        padding: SPACING.lg,
        zIndex: 201,
    },
    threadModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: SPACING.lg,
    },
    threadModalTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: colors.text,
        flex: 1,
        marginRight: SPACING.sm,
    },
    closeBtn: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: colors.border,
    },
    threadEntry: {
        backgroundColor: colors.background,
        borderRadius: RADIUS.md,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
        borderLeftWidth: 2,
        borderLeftColor: colors.primary,
    },
    threadEntryContent: {
        fontSize: 14,
        color: colors.text,
        lineHeight: 20,
    },
    threadEntryDate: {
        fontSize: 11,
        color: colors.textSecondary,
        marginTop: 6,
    },
    addThreadRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: SPACING.sm,
        marginTop: SPACING.md,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        paddingTop: SPACING.md,
    },
    threadInput: {
        flex: 1,
        fontSize: 14,
        color: colors.text,
        backgroundColor: colors.background,
        borderRadius: RADIUS.md,
        padding: SPACING.sm,
        maxHeight: 100,
        borderWidth: 1,
        borderColor: colors.border,
    },
    sendBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    syncBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 6,
        gap: 6,
    },
    syncText: {
        fontSize: 11,
        color: colors.textSecondary,
    },
});
