name: Sync Other Branches
on:
  push:
    branches:
      - main
      - akshata
      - manjiri

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Sync other branches into pushed branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          BRANCHES=("main" "akshata" "manjiri")

          git fetch origin

          echo "Syncing into $CURRENT_BRANCH..."

          # Checkout the pushed branch and pull latest
          git checkout $CURRENT_BRANCH
          git pull origin $CURRENT_BRANCH

          for BRANCH in "${BRANCHES[@]}"; do
            if [ "$BRANCH" != "$CURRENT_BRANCH" ]; then
              echo "Merging $BRANCH into $CURRENT_BRANCH..."
              if git merge origin/$BRANCH --no-ff -m "Merge $BRANCH into $CURRENT_BRANCH"; then
                git push origin $CURRENT_BRANCH
                echo "Successfully merged $BRANCH into $CURRENT_BRANCH"
              else
                echo "Merge conflict: could not merge $BRANCH into $CURRENT_BRANCH"
                git merge --abort
                gh pr create --base $CURRENT_BRANCH --head $BRANCH --title "Conflict: Merge $BRANCH into $CURRENT_BRANCH" --body "Please resolve the conflict manually."
              fi
            fi
          done
